// ============================================================
// Learning Hub — Rich Mock Data
// ============================================================

export const learnerProfile = {
  name: 'Alex Carter',
  hoursThisMonth: 24,
  hoursThisYear: 187,
  coursesCompleted: 14,
  coursesInProgress: 3,
  currentStreak: 8,
  longestStreak: 21,
  learningScore: 87,
  targetRole: 'Principal AI Engineer',
};

export const learningPaths = [
  {
    id: 'lp1',
    title: 'AI Engineering Mastery',
    description: 'Deep dive into production AI systems, MLOps, and advanced architectures',
    progress: 68,
    totalCourses: 12,
    completedCourses: 8,
    estimatedHours: 48,
    dueDate: 'Sep 2024',
    tags: ['AI', 'MLOps', 'Python'],
    color: '#7c3aed',
    recommended: true,
    instructor: 'Dr. Lena Park',
    platform: 'Internal Academy',
  },
  {
    id: 'lp2',
    title: 'Cloud Architecture Pro',
    description: 'AWS/GCP/Azure multi-cloud design patterns and certifications',
    progress: 35,
    totalCourses: 9,
    completedCourses: 3,
    estimatedHours: 36,
    dueDate: 'Oct 2024',
    tags: ['Cloud', 'AWS', 'Architecture'],
    color: '#06b6d4',
    recommended: false,
    instructor: 'Marcus Chen',
    platform: 'Coursera',
  },
  {
    id: 'lp3',
    title: 'Engineering Leadership',
    description: 'Transition from IC to tech lead with strategic thinking and people skills',
    progress: 15,
    totalCourses: 8,
    completedCourses: 1,
    estimatedHours: 32,
    dueDate: 'Dec 2024',
    tags: ['Leadership', 'Management', 'Strategy'],
    color: '#f59e0b',
    recommended: true,
    instructor: 'Sarah Williams',
    platform: 'LinkedIn Learning',
  },
];

export const skillGaps = [
  { skill: 'LLM Fine-tuning', currentLevel: 45, targetLevel: 90, gap: 45, priority: 'Critical', category: 'AI & ML', color: '#7c3aed' },
  { skill: 'Kubernetes & Helm', currentLevel: 55, targetLevel: 85, gap: 30, priority: 'High', category: 'Engineering', color: '#06b6d4' },
  { skill: 'Strategic Planning', currentLevel: 50, targetLevel: 80, gap: 30, priority: 'High', category: 'Leadership', color: '#f59e0b' },
  { skill: 'Vector Databases', currentLevel: 30, targetLevel: 80, gap: 50, priority: 'Critical', category: 'AI & ML', color: '#7c3aed' },
  { skill: 'Technical Writing', currentLevel: 65, targetLevel: 85, gap: 20, priority: 'Medium', category: 'Communication', color: '#10b981' },
  { skill: 'System Design', currentLevel: 70, targetLevel: 90, gap: 20, priority: 'Medium', category: 'Engineering', color: '#06b6d4' },
];

export const certifications = [
  {
    id: 'cert1',
    name: 'AWS Solutions Architect – Professional',
    issuer: 'Amazon Web Services',
    status: 'completed',
    completedDate: 'Mar 2024',
    expiryDate: 'Mar 2027',
    expiresInDays: null,
    credentialId: 'AWS-SAP-2024-AC7821',
    emoji: '☁️',
    color: '#f59e0b',
    score: 89,
  },
  {
    id: 'cert2',
    name: 'TensorFlow Developer Certificate',
    issuer: 'Google',
    status: 'completed',
    completedDate: 'Jan 2024',
    expiryDate: 'Jan 2027',
    expiresInDays: null,
    credentialId: 'TF-DEV-2024-1094',
    emoji: '🤖',
    color: '#7c3aed',
    score: 94,
  },
  {
    id: 'cert3',
    name: 'Kubernetes Administrator (CKA)',
    issuer: 'CNCF',
    status: 'in_progress',
    completedDate: null,
    expiryDate: null,
    expiresInDays: null,
    credentialId: null,
    emoji: '⚙️',
    color: '#06b6d4',
    progress: 72,
    examDate: 'Aug 15, 2024',
  },
  {
    id: 'cert4',
    name: 'Professional Scrum Master II',
    issuer: 'Scrum.org',
    status: 'completed',
    completedDate: 'Sep 2023',
    expiryDate: 'Never',
    expiresInDays: null,
    credentialId: 'PSM-II-SG-8821',
    emoji: '🎯',
    color: '#10b981',
    score: 88,
  },
  {
    id: 'cert5',
    name: 'Google Cloud Professional Data Engineer',
    issuer: 'Google Cloud',
    status: 'planned',
    completedDate: null,
    expiryDate: null,
    expiresInDays: null,
    credentialId: null,
    emoji: '📊',
    color: '#06b6d4',
    progress: 0,
    examDate: 'Nov 2024',
  },
];

export const learningFeed = [
  {
    id: 'lf1',
    type: 'article',
    title: 'RAG vs Fine-tuning: When to Use Each for Production LLMs',
    source: 'Towards Data Science',
    readTime: '8 min',
    relevance: 98,
    tags: ['LLM', 'AI Engineering', 'Production'],
    emoji: '📰',
    color: '#7c3aed',
    published: '2 hours ago',
  },
  {
    id: 'lf2',
    type: 'video',
    title: 'Advanced Kubernetes Patterns for ML Workloads',
    source: 'KubeCon 2024',
    readTime: '32 min',
    relevance: 91,
    tags: ['Kubernetes', 'MLOps', 'Cloud'],
    emoji: '🎬',
    color: '#06b6d4',
    published: '1 day ago',
  },
  {
    id: 'lf3',
    type: 'course',
    title: 'Vector Embeddings & Semantic Search Fundamentals',
    source: 'DeepLearning.AI',
    readTime: '4 hours',
    relevance: 96,
    tags: ['Vector DB', 'Embeddings', 'AI'],
    emoji: '🎓',
    color: '#10b981',
    published: '3 days ago',
  },
  {
    id: 'lf4',
    type: 'paper',
    title: 'Mixture of Experts: Scaling LLMs Efficiently',
    source: 'arXiv',
    readTime: '20 min',
    relevance: 85,
    tags: ['Research', 'LLM', 'Scaling'],
    emoji: '📄',
    color: '#f59e0b',
    published: '5 days ago',
  },
  {
    id: 'lf5',
    type: 'podcast',
    title: 'The Engineering Manager\'s Guide to AI Teams',
    source: 'Software Engineering Daily',
    readTime: '45 min',
    relevance: 82,
    tags: ['Leadership', 'AI Teams', 'Management'],
    emoji: '🎙️',
    color: '#ec4899',
    published: '1 week ago',
  },
];

export const courseLibrary = [
  { id: 'c1', title: 'Deep Learning Specialization', provider: 'Coursera', hours: 64, level: 'Advanced', status: 'available', rating: 4.9, enrolled: 2841, tags: ['Deep Learning', 'TensorFlow', 'AI'], emoji: '🧠', color: '#7c3aed' },
  { id: 'c2', title: 'System Design Interview Masterclass', provider: 'Educative', hours: 40, level: 'Intermediate', status: 'in_progress', progress: 48, rating: 4.8, enrolled: 1203, tags: ['Architecture', 'System Design'], emoji: '🏗️', color: '#06b6d4' },
  { id: 'c3', title: 'AWS Cloud Practitioner Essentials', provider: 'AWS', hours: 12, level: 'Beginner', status: 'completed', rating: 4.7, enrolled: 5021, tags: ['Cloud', 'AWS'], emoji: '☁️', color: '#f59e0b' },
  { id: 'c4', title: 'The Manager\'s Path', provider: 'O\'Reilly', hours: 20, level: 'Intermediate', status: 'available', rating: 4.8, enrolled: 891, tags: ['Leadership', 'Management'], emoji: '🎯', color: '#10b981' },
  { id: 'c5', title: 'LangChain & LLM Application Development', provider: 'DeepLearning.AI', hours: 24, level: 'Advanced', status: 'available', rating: 4.9, enrolled: 1452, tags: ['LLM', 'LangChain', 'Python'], emoji: '⛓️', color: '#7c3aed' },
  { id: 'c6', title: 'Data Engineering Zoomcamp', provider: 'DataTalks.Club', hours: 80, level: 'Advanced', status: 'available', rating: 4.7, enrolled: 3210, tags: ['Data Engineering', 'Spark', 'dbt'], emoji: '🔧', color: '#ec4899' },
];

export const weeklySchedule = [
  { day: 'Mon', topic: 'LLM Fine-tuning Lab', duration: '45 min', status: 'completed', color: '#10b981' },
  { day: 'Tue', topic: 'CKA Exam Prep — Networking', duration: '30 min', status: 'completed', color: '#10b981' },
  { day: 'Wed', topic: 'System Design: Distributed Systems', duration: '60 min', status: 'in_progress', color: '#f59e0b' },
  { day: 'Thu', topic: 'Vector Database Workshop', duration: '45 min', status: 'upcoming', color: '#64748b' },
  { day: 'Fri', topic: 'Engineering Leadership Seminar', duration: '30 min', status: 'upcoming', color: '#64748b' },
];

export const monthlyHours = [
  { month: 'Feb', hours: 18 },
  { month: 'Mar', hours: 26 },
  { month: 'Apr', hours: 21 },
  { month: 'May', hours: 32 },
  { month: 'Jun', hours: 28 },
  { month: 'Jul', hours: 24 },
];
