"""add_organization_models

Revision ID: d49f3fc69094
Revises: 611d94483df2
Create Date: 2026-08-03 15:11:31.940479
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd49f3fc69094'
down_revision: Union[str, None] = '611d94483df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('total_headcount', sa.Integer(), nullable=False),
    sa.Column('voluntary_attrition_rate', sa.Float(), nullable=False),
    sa.Column('involuntary_attrition_rate', sa.Float(), nullable=False),
    sa.Column('new_hires', sa.Integer(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('enps', sa.Integer(), nullable=False),
    sa.Column('training_hours_per_employee', sa.Float(), nullable=False),
    sa.Column('absenteeism_rate', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('operating_cost', sa.Float(), nullable=False),
    sa.Column('ebitda', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('marketing_spend', sa.Float(), nullable=False),
    sa.Column('rd_spend', sa.Float(), nullable=False),
    sa.Column('overall_productivity_score', sa.Integer(), nullable=False),
    sa.Column('csat', sa.Float(), nullable=False),
    sa.Column('nps', sa.Integer(), nullable=False),
    sa.Column('market_share_percentage', sa.Float(), nullable=False),
    sa.Column('project_completion_rate', sa.Float(), nullable=False),
    sa.Column('carbon_footprint_tons', sa.Integer(), nullable=False),
    sa.Column('energy_consumption_kwh', sa.Integer(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('security_incidents', sa.Integer(), nullable=False),
    sa.Column('anomaly_flag', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('target_metric', sa.String(length=100), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.Column('predicted_impact_percentage', sa.Float(), nullable=False),
    sa.Column('predicted_roi', sa.Float(), nullable=False),
    sa.Column('time_to_impact_months', sa.Integer(), nullable=False),
    sa.Column('ai_recommendation', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_scenarios')
    op.drop_table('organization_metrics')
    # ### end Alembic commands ###
