-- Employee Digital Twin operational schema
-- Target: SQL database in Microsoft Fabric
-- IDs stay NVARCHAR so existing text UUID values are preserved exactly.


-- Demo data is built in Python because it includes password hashes and
-- cross-table relationships generated by backend/scripts/seed_database.py.
-- After the schema scripts succeed, run:
--   cd backend && python -m scripts.seed_database
-- Organization demo rows:
--   cd backend && python -m scripts.seed_organization_data
